### ISSUE TITLE
数据已失效

### ISSUE THREAD

**Issue by bbbbbbbin** [wanlida/2018_datacastle_tap4fun_consumption_predict#1]
是否可以再提供一下数据，感谢

**Comment by wanlida** [comment]
链接: https://pan.baidu.com/s/19mkHCOGCkBCtNCxC8jcuxg 提取码: kz19


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bbbbbbbin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 中午11:45
收件人:&nbsp;"wanlida/2018_datacastle_tap4fun_consumption_predict"<2018_datacastle_tap4fun_consumption_predict@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wanlida/2018_datacastle_tap4fun_consumption_predict] 数据已失效 (#1)





 
是否可以再提供一下数据，感谢

**Comment by bbbbbbbin** [comment]
感谢。
